import * as Knex from 'knex';

exports.seed = (knex: Knex) => {
    return knex("restaurants").del().then(() => {
        return knex("districts").del().then(() => {
            return knex("districts").insert([               
                {id: 1002, region: 'Hong Kong Island', name: 'The Peak'},
                {id: 1004, region: 'Hong Kong Island', name: 'North Point'},
                {id: 1005, region: 'Hong Kong Island', name: 'Mid-Levels'},
                {id: 1007, region: 'Hong Kong Island', name: 'Shek O'},
                {id: 1009, region: 'Hong Kong Island', name: 'Sai Wan Ho'},
                {id: 1010, region: 'Hong Kong Island', name: 'Stanley'},  
                {id: 1011, region: 'Hong Kong Island', name: 'Admiralty'},  
                {id: 1012, region: 'Hong Kong Island', name: 'Aberdeen'},  
                {id: 1013, region: 'Hong Kong Island', name: 'Chai Wan'}, 
                {id: 1014, region: 'Hong Kong Island', name: 'Quarry Bay'}, 
                {id: 1015, region: 'Hong Kong Island', name: 'Repulse Bay'}, 
                {id: 1016, region: 'Hong Kong Island', name: 'Deep Water Bay'},
                {id: 1017, region: 'Hong Kong Island', name: 'Happy Valley'}, 
                {id: 1018, region: 'Hong Kong Island', name: 'Shau Kei Wan'},
                {id: 1019, region: 'Hong Kong Island', name: 'Causeway Bay'}, 
                {id: 1020, region: 'Hong Kong Island', name: 'Ap Lei Chau'},
                {id: 1021, region: 'Hong Kong Island', name: 'Pok Fu Lam'},
                {id: 1022, region: 'Hong Kong Island', name: 'Wan Chai'}, 
                {id: 1023, region: 'Hong Kong Island', name: 'Tai Koo'}, 
                {id: 1024, region: 'Hong Kong Island', name: 'Heng Fa Chuen'},
                {id: 1025, region: 'Hong Kong Island', name: 'Tai Hang'}, 
                {id: 1026, region: 'Hong Kong Island', name: 'Tin Hau'}, 
                {id: 1027, region: 'Hong Kong Island', name: 'Wong Chuk Hang'},
                {id: 2001, region: 'Kowloon', name: 'Kowloon City'}, 
                {id: 2002, region: 'Kowloon', name: 'Kowloon Tong'}, 
                {id: 2003, region: 'Kowloon', name: 'Kowloon Bay'}, 
                {id: 2004, region: 'Kowloon', name: 'To Kwa Wan'},
                {id: 2005, region: 'Kowloon', name: 'Tai Kok Tsui'},
                {id: 2006, region: 'Kowloon', name: 'Ngau Tau Kok'},
                {id: 2007, region: 'Kowloon', name: 'Shek Kip Mei'},
                {id: 2008, region: 'Kowloon', name: 'Tsim Sha Tsui'},
                {id: 2009, region: 'Kowloon', name: 'Ho Man Tin'},
                {id: 2010, region: 'Kowloon', name: 'Mong Kok'}, 
                {id: 2011, region: 'Kowloon', name: 'Yau Ma Tei'},
                {id: 2012, region: 'Kowloon', name: 'Yau Tong'}, 
                {id: 2013, region: 'Kowloon', name: 'Cheung Sha Wan'},
                {id: 2015, region: 'Kowloon', name: 'Hung Hom'}, 
                {id: 2016, region: 'Kowloon', name: 'Lai Chi Kok'},
                {id: 2019, region: 'Kowloon', name: 'Sham Shui Po'},
                {id: 2020, region: 'Kowloon', name: 'Wong Tai Sin'},
                {id: 2021, region: 'Kowloon', name: 'Tsz Wan Shan'},
                {id: 2022, region: 'Kowloon', name: 'San Po Kong'},
                {id: 2024, region: 'Kowloon', name: 'Lam Tin'}, 
                {id: 2025, region: 'Kowloon', name: 'Lei Yue Mun'},
                {id: 2026, region: 'Kowloon', name: 'Kwun Tong'},
                {id: 2027, region: 'Kowloon', name: 'Diamond Hill'}, 
                {id: 2028, region: 'Kowloon', name: 'Jordan'},  
                {id: 2029, region: 'Kowloon', name: 'Prince Edward'},
                {id: 2030, region: 'Kowloon', name: 'Lok Fu'},
                {id: 2031, region: 'Kowloon', name: 'Mei Foo'}, 
                {id: 2032, region: 'Kowloon', name: 'Choi Hung'}, 
                {id: 3001, region: 'New Territories', name: 'Sheung Shui'}, 
                {id: 3002, region: 'New Territories', name: 'Tai Po'}, 
                {id: 3003, region: 'New Territories', name: 'Yuen Long'}, 
                {id: 3004, region: 'New Territories', name: 'Tin Shui Wai'},
                {id: 3005, region: 'New Territories', name: 'Tuen Mun'}, 
                {id: 3006, region: 'New Territories', name: 'Sai Kung'}, 
                {id: 3007, region: 'New Territories', name: 'Sha Tin'}, 
                {id: 3008, region: 'New Territories', name: 'Fanling'},  
                {id: 3009, region: 'New Territories', name: 'Ma On Shan'},
                {id: 3012, region: 'New Territories', name: 'Tai Wai'}, 
                {id: 3013, region: 'New Territories', name: 'Fo Tan'}, 
                {id: 3014, region: 'New Territories', name: 'Tai Wo'}, 
                {id: 3015, region: 'New Territories', name: 'Kwai Fong'}, 
                {id: 3016, region: 'New Territories', name: 'Lau Fau shan'},
                {id: 3017, region: 'New Territories', name: 'Tsing Yi' },
                {id: 3018, region: 'New Territories', name: 'Tsuen Wan'},
                {id: 3019, region: 'New Territories', name: 'Kwai Chung'},
                {id: 3020, region: 'New Territories', name: 'Tseung Kwan O'},
                {id: 3022, region: 'New Territories', name: 'Ma Wan'}
            ]);
        });
    });
};
